// Generated by scripts/convert-mathmaster.cjs: e-book manifest
export interface TextbookBook { chapter: string; label: string; file: string; }
export interface TextbookGroup { subject: string; moduleId: string; icon: string; books: TextbookBook[]; }
export const TEXTBOOK_GROUPS: TextbookGroup[] = [
  {
    "subject": "概率论与数理统计",
    "moduleId": "probability",
    "icon": "🎲",
    "books": [
      {
        "chapter": "随机事件与概率",
        "label": "随机事件与概率（讲义）",
        "file": "/textbooks/probability/random-events-and-probability-notes.pdf"
      },
      {
        "chapter": "随机事件与概率",
        "label": "随机事件与概率（习题）",
        "file": "/textbooks/probability/random-events-and-probability-exercises.pdf"
      },
      {
        "chapter": "随机变量及其分布",
        "label": "随机变量及其分布（讲义）",
        "file": "/textbooks/probability/random-variables-and-distribution-notes.pdf"
      },
      {
        "chapter": "随机变量及其分布",
        "label": "随机变量及其分布（习题）",
        "file": "/textbooks/probability/random-variables-and-distribution-exercises.pdf"
      },
      {
        "chapter": "随机变量数字特征",
        "label": "随机变量数字特征（讲义）",
        "file": "/textbooks/probability/digital-features-notes.pdf"
      },
      {
        "chapter": "随机变量数字特征",
        "label": "随机变量数字特征（习题）",
        "file": "/textbooks/probability/digital-features-exercises.pdf"
      },
      {
        "chapter": "大数定律与中心极限定理",
        "label": "大数定律与中心极限定理（讲义）",
        "file": "/textbooks/probability/law-of-large-numbers-and-central-limit-theorem-notes.pdf"
      },
      {
        "chapter": "大数定律与中心极限定理",
        "label": "大数定律与中心极限定理（习题）",
        "file": "/textbooks/probability/law-of-large-numbers-and-central-limit-theorem-exercises.pdf"
      },
      {
        "chapter": "标题",
        "label": "标题（讲义）",
        "file": "/textbooks/probability/mathematical-statistics-notes.pdf"
      },
      {
        "chapter": "标题",
        "label": "标题（习题）",
        "file": "/textbooks/probability/mathematical-statistics-exercises.pdf"
      }
    ]
  }
];
