// 答题记录与社区帖子的后端同步（Supabase，最佳努力：失败不影响本地）
import { answersAPI, postsAPI } from '@/lib/api-client';
import { hasApiToken } from '@/lib/api-auth';
import { createAnswerRecord, getAnswerRecordById, createPost, getPostById } from '@/lib/db';
import type { AnswerRecord, Post } from '@/types';

let lastPostsMergeAt = 0;
let lastAnswersMergeAt = 0;
const MERGE_INTERVAL = 30 * 1000;

/** 后端答题记录 → 前端 AnswerRecord（缺少的本地字段用默认值） */
export function mapApiAnswerToLocal(a: any): AnswerRecord {
  return {
    id: a.id,
    userId: a.userId,
    questionId: a.questionId,
    content: a.content,
    images: a.images || [],
    submittedAt: a.submittedAt,
    aiScore: a.aiScore ?? 0,
    aiFeedback: a.aiFeedback || '',
    isCorrect: !!a.isCorrect,
    experienceGained: a.experienceGained ?? 0,
    isPublic: !!a.isPublic,
    likes: a.likes ?? 0,
    likedBy: a.likedBy || [],
    comments: [],
  };
}

/** 后端帖子 → 前端 Post（缺少的本地字段用默认值） */
export function mapApiPostToLocal(p: any): Post {
  return {
    id: p.id,
    userId: p.userId,
    userNickname: p.user?.nickname || '',
    userAvatar: p.user?.avatar || '👤',
    moduleId: p.moduleId || 'general',
    postType: p.postType || 'question',
    title: p.title,
    content: p.content,
    topics: p.topics || [],
    images: p.images || [],
    commentPermission: 'all',
    mentions: [],
    createdAt: p.createdAt,
    likes: p.likes ?? 0,
    likedBy: p.likedBy || [],
    comments: [],
  };
}

/** 登录态下同步答题记录到后端（题目不存在时后端会自动建档） */
export async function syncAnswerToBackend(
  record: AnswerRecord,
  question: {
    id: string;
    moduleId: string;
    date: string;
    title: string;
    content: string;
    images?: string[];
    answer?: string;
    answerImages?: string[];
    difficulty?: number;
    isAutoGenerated?: boolean;
  }
): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await answersAPI.submit({
      id: record.id,
      questionId: record.questionId,
      content: record.content,
      images: record.images,
      isPublic: record.isPublic,
      question,
    });
  } catch (error) {
    console.warn('同步答题记录到后端失败:', error);
  }
}

/** 登录态下同步答题记录的更新（公开状态等） */
export async function syncAnswerUpdateToBackend(record: AnswerRecord): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await answersAPI.update(record.id, {
      isPublic: record.isPublic,
      likes: record.likes,
      likedBy: record.likedBy,
    });
  } catch (error) {
    console.warn('同步答题记录更新到后端失败:', error);
  }
}

/** 登录态下同步删除答题记录 */
export async function syncAnswerDeleteToBackend(answerId: string): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await answersAPI.remove(answerId);
  } catch (error) {
    console.warn('同步删除答题记录到后端失败:', error);
  }
}

/** 登录态下把后端答题记录合并进本地（不覆盖本地已有记录） */
export async function mergeAnswersFromBackend(): Promise<void> {
  if (!hasApiToken()) return;
  const now = Date.now();
  if (now - lastAnswersMergeAt < MERGE_INTERVAL) return;
  lastAnswersMergeAt = now;

  try {
    const res = await answersAPI.getMyAnswers();
    for (const apiAnswer of res.answers || []) {
      try {
        const existing = await getAnswerRecordById(apiAnswer.id);
        if (!existing) {
          await createAnswerRecord(mapApiAnswerToLocal(apiAnswer));
        }
      } catch (error) {
        console.warn('合并答题记录失败:', error);
      }
    }
  } catch (error) {
    console.warn('拉取后端答题记录失败:', error);
  }
}

/** 登录态下同步帖子到后端 */
export async function syncPostToBackend(post: Post): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await postsAPI.create({
      id: post.id,
      title: post.title,
      content: post.content,
      moduleId: post.moduleId,
      images: post.images,
      postType: post.postType,
      topics: post.topics || [],
    });
  } catch (error) {
    console.warn('同步帖子到后端失败:', error);
  }
}

/** 登录态下同步帖子的更新 */
export async function syncPostUpdateToBackend(post: Post): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await postsAPI.update(post.id, {
      title: post.title,
      content: post.content,
      moduleId: post.moduleId,
      images: post.images,
      postType: post.postType,
      topics: post.topics || [],
      likes: post.likes,
      likedBy: post.likedBy,
    });
  } catch (error) {
    console.warn('同步帖子更新到后端失败:', error);
  }
}

/** 登录态下同步删除帖子 */
export async function syncPostDeleteToBackend(postId: string): Promise<void> {
  if (!hasApiToken()) return;
  try {
    await postsAPI.remove(postId);
  } catch (error) {
    console.warn('同步删除帖子到后端失败:', error);
  }
}

/** 登录态下把后端帖子合并进本地（不覆盖本地已有记录；带30秒节流） */
export async function mergePostsFromBackend(): Promise<void> {
  if (!hasApiToken()) return;
  const now = Date.now();
  if (now - lastPostsMergeAt < MERGE_INTERVAL) return;
  lastPostsMergeAt = now;

  try {
    const res = await postsAPI.getList(1, 100);
    for (const apiPost of res.posts || []) {
      try {
        const existing = await getPostById(apiPost.id);
        if (!existing) {
          await createPost(mapApiPostToLocal(apiPost));
        }
      } catch (error) {
        console.warn('合并帖子失败:', error);
      }
    }
  } catch (error) {
    console.warn('拉取后端帖子失败:', error);
  }
}
