// 用户类型
export interface User {
  id: string;
  nickname: string;
  passwordHash: string;
  avatar: string;
  // 模块独立经验值系统
  moduleData: {
    math: { exp: number; level: number; selectedTitle: string | null };
  };
  // 用户选择的主展示模块（决定显示哪个模块的称号）
  displayCategory?: 'math';
  // 收藏的帖子ID列表
  favoritePosts?: string[];
  // 收藏的每日一题ID列表
  favoriteQuestions?: string[];
  // 关注列表
  following?: string[];
  // 个性签名
  bio?: string;
  // 个人主页封面背景图（data URL 或 http 链接）
  coverImage?: string;
  // 隐私设置
  privacy?: {
    showFollowing: boolean;  // 是否显示关注列表
    showFollowers: boolean;  // 是否显示粉丝列表
    showBio: boolean;        // 是否显示个性签名
  };
  // π力系统数据
  piPower: {
    currentPi: number;           // 当前总π力
    monthlyPi: number;           // 本月π力
    totalAnswered: number;       // 累计答对题数
    monthlyAnswered: number;     // 本月答对题数
    lastAnswerDate: string | null; // 最后答题日期
    currentStreak: number;       // 连续答对天数
    monthlyResetDate: string;    // 下次清零日期
    dailyAttempts: Record<string, number>; // 每日尝试次数（日期->次数）
    questionPi?: Record<string, number>;   // 每题已获得的π力（题目ID->π值，每题上限2π）
  };
  // 用户位置信息
  location?: {
    province: string;  // 省份
    city?: string;     // 城市（可选）
    updatedAt: string; // 更新时间
  };
  // 欧拉称号历史记录
  eulerTitleHistory: {
    id: string;
    title: string;      // 称号名称
    province?: string;  // 省份
    rankType: 'province' | 'global';
    rank: number;
    obtainedAt: string;
    month: string;      // YYYY-MM
  }[];
  // 当前生效的欧拉称号（每月评选）
  currentEulerTitle?: {
    title: string;
    province?: string;
    rankType: 'province' | 'global';
    rank: number;
    obtainedAt: string;
    month: string;
  };
  // 兼容旧数据，保留以下字段
  level?: number;
  experience?: number;
  title?: string;
  frame?: string;
  isAdmin: boolean;
  createdAt: string;
  lastLoginAt: string;
}

// 导出游戏化相关类型
export * from './gamification';

// 知识模块类型
export interface KnowledgeModule {
  id: string;
  name: string;
  category: 'math';
  icon: string;
  color: string;
  description: string;
  topics: Topic[];
}

export interface Topic {
  id: string;
  title: string;
  difficulty: number;
  content?: string;
}

// 每日一题类型
export interface DailyQuestion {
  id: string;
  moduleId: string;
  date: string;
  title: string;
  content: string;
  images: string[];
  answer: string;
  answerImages: string[];
  difficulty: number;
  authorId?: string;
  isAutoGenerated: boolean;
  createdAt: string;
  // 题目审核状态：草稿 → 已审核 → 已发布
  reviewStatus?: 'draft' | 'reviewed' | 'published';
}

// 答题记录类型
export interface AnswerRecord {
  id: string;
  userId: string;
  questionId: string;
  content: string;
  images: string[];
  submittedAt: string;
  aiScore: number;
  aiFeedback: string;
  isCorrect: boolean;
  experienceGained: number;
  isPublic: boolean; // 是否公开答案
  likes: number; // 点赞数
  likedBy: string[]; // 点赞用户ID列表
  comments: AnswerComment[]; // 评论列表
  note?: string; // 用户备注
  // 双通道批改元数据
  gradingMeta?: GradingMeta;
}

// 得分点拆解项
export interface ScorePoint {
  point: string;      // 得分点描述
  earned: boolean;    // 是否得分
  comment: string;    // 评语
}

// 双通道批改元数据
export interface GradingMeta {
  localScore: number;        // 本地算法得分
  aiScore?: number;          // AI 二次批改得分（未触发时为空）
  needsReview: boolean;      // 两通道分歧过大，待人工复核
  breakdown?: ScorePoint[];  // 得分点拆解
}

// 答案评论类型
export interface AnswerComment {
  id: string;
  answerId: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  content: string;
  createdAt: string;
}

// 社区帖子类型
export interface Post {
  id: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  moduleId: string;

  // 新增字段
  postType: PostType;           // 帖子类型
  title: string;
  content: string;
  topics: string[];             // 话题标签
  images: string[];
  location?: Location;          // 位置信息
  commentPermission: CommentPermission;  // 评论权限

  // 投票功能
  poll?: Poll;

  // @提及
  mentions: string[];           // 被提及的用户ID

  createdAt: string;
  likes: number;
  likedBy: string[];
  comments: Comment[];
}

export interface Comment {
  id: string;
  postId: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  content: string;
  createdAt: string;
}

// 游戏化状态
export interface GamificationState {
  dailyAnswered: boolean;
  dailyPosted: boolean;
  lastCheckDate: string;
}

// 帖子类型
export type PostType = 'question' | 'article' | 'answer' | 'thought';

// 评论权限
export type CommentPermission = 'all' | 'followers' | 'none';

// 投票选项
export interface PollOption {
  id: string;
  text: string;
  votes: number;
  votedBy: string[];
}

// 投票
export interface Poll {
  question: string;
  options: PollOption[];
  endTime?: string;
  multiple: boolean;
}

// 位置信息
export interface Location {
  province: string;
  city?: string;
  address?: string;
}

// 消息类型
export interface Message {
  id: string;
  senderId: string;
  receiverId: string;
  content: string;
  images: string[];
  createdAt: string;
  isRead: boolean;
  // 消息类型：普通文本/图片、每日一题卡片、帖子卡片
  messageType?: 'text' | 'question-card' | 'post-card';
  // 卡片负载（messageType 非 text 时使用）
  cardPayload?: QuestionCardPayload | PostCardPayload;
}

// 每日一题分享卡片负载
export interface QuestionCardPayload {
  kind: 'question-card';
  questionId: string;
  questionTitle: string;
  questionContent: string;
  moduleId: string;
  date: string;
  difficulty: number;
  // 分享者的答题结果（可选）
  isCorrect?: boolean;
  score?: number;
  streak?: number;
}

// 帖子分享卡片负载
export interface PostCardPayload {
  kind: 'post-card';
  postId: string;
  title: string;
  contentPreview: string;
  moduleId: string;
  authorNickname: string;
  authorAvatar: string;
  likes: number;
  commentCount: number;
}

// 聊天会话
export interface ChatSession {
  userId: string;
  friendId: string;
  lastMessage: Message;
  unreadCount: number;
  updatedAt: string;
}

// 讨论区消息的回复（快照昵称/头像，避免额外查用户表）
export interface DiscussionReply {
  id: string;
  userId: string;
  userNickname: string;
  userAvatar?: string;
  content: string;
  replyToNickname?: string; // 回复某条回复时 @ 对方
  likes?: number;
  likedBy?: string[];
  createdAt: string;
}

// 讨论区消息（每日挑战讨论区：用户主动发送，可引用题目 / 自己的解答）
export interface DiscussionMessage {
  id: string;
  questionId: string; // 所属讨论区（题目 id）
  userId: string;
  content: string;
  // 引用题目快照（可选）
  refQuestionId?: string;
  refQuestionTitle?: string;
  refQuestionModuleId?: string;
  refQuestionDate?: string;
  // 引用自己解答的快照（可选；发布时截取，避免泄露私密答案原文）
  refAnswerId?: string;
  refAnswerExcerpt?: string;
  refAnswerScore?: number;
  refAnswerIsCorrect?: boolean;
  // 点赞 / 回复（可选：兼容 v7 时期的旧记录）
  likes?: number;
  likedBy?: string[];
  replies?: DiscussionReply[];
  createdAt: string;
}

// 笔记类型
export interface Note {
  id: string;
  userId: string;
  moduleId: string;
  chapterTitle: string;
  title?: string; // 旧数据的标题（新笔记不再使用，全部作为正文）
  content?: string; // 便签文本内容
  canvasData?: string; // base64 PNG（涂鸦层，已废弃）
  positionX?: number; // 百分比位置 0-100
  positionY?: number;
  createdAt: string;
  updatedAt: string;
}

// 导入的自定义课时内容块
export interface LessonBlock {
  id: string;
  type: 'text' | 'image' | 'formula' | 'example';
  content: string;
  width?: number;
  height?: number;
}

// 导入课时的例题
export interface LessonExample {
  id: string;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

// 通过导入管线创建的自定义课时
export interface CustomLesson {
  id: string;
  moduleId: string;
  title: string;
  blocks: LessonBlock[];
  examples?: LessonExample[];
  sourceName: string; // 来源文件名
  status: 'draft' | 'published';
  createdAt: string;
}
