// 用户类型
export interface User {
  id: string;
  nickname: string;
  passwordHash: string;
  avatar: string;
  // 模块独立经验值系统
  moduleData: {
    math: { exp: number; level: number; selectedTitle: string | null };
    physics: { exp: number; level: number; selectedTitle: string | null };
    cs: { exp: number; level: number; selectedTitle: string | null };
  };
  // 用户选择的主展示模块（决定显示哪个模块的称号）
  displayCategory?: 'math' | 'physics' | 'cs';
  // 收藏的帖子ID列表
  favoritePosts?: string[];
  // 兼容旧数据，保留以下字段
  level?: number;
  experience?: number;
  title?: string;
  frame?: string;
  isAdmin: boolean;
  createdAt: string;
  lastLoginAt: string;
}

// 导出游戏化相关类型
export * from './gamification';

// 知识模块类型
export interface KnowledgeModule {
  id: string;
  name: string;
  category: 'math' | 'physics' | 'cs';
  icon: string;
  color: string;
  description: string;
  topics: Topic[];
}

export interface Topic {
  id: string;
  title: string;
  difficulty: number;
  content?: string;
}

// 每日一题类型
export interface DailyQuestion {
  id: string;
  moduleId: string;
  date: string;
  title: string;
  content: string;
  images: string[];
  answer: string;
  answerImages: string[];
  difficulty: number;
  authorId?: string;
  isAutoGenerated: boolean;
  createdAt: string;
}

// 答题记录类型
export interface AnswerRecord {
  id: string;
  userId: string;
  questionId: string;
  content: string;
  images: string[];
  submittedAt: string;
  aiScore: number;
  aiFeedback: string;
  isCorrect: boolean;
  experienceGained: number;
  isPublic: boolean; // 是否公开答案
  likes: number; // 点赞数
  likedBy: string[]; // 点赞用户ID列表
  comments: AnswerComment[]; // 评论列表
}

// 答案评论类型
export interface AnswerComment {
  id: string;
  answerId: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  content: string;
  createdAt: string;
}

// 社区帖子类型
export interface Post {
  id: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  moduleId: string;
  title: string;
  content: string;
  images: string[];
  createdAt: string;
  likes: number;
  likedBy: string[];
  comments: Comment[];
}

export interface Comment {
  id: string;
  postId: string;
  userId: string;
  userNickname: string;
  userAvatar: string;
  content: string;
  createdAt: string;
}

// 游戏化状态
export interface GamificationState {
  dailyAnswered: boolean;
  dailyPosted: boolean;
  lastCheckDate: string;
}
