import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken } from '@/lib/auth';

// 提交答案
export async function POST(request: NextRequest) {
  try {
    const token = request.headers.get('authorization')?.replace('Bearer ', '');

    if (!token) {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }

    const payload = verifyToken(token);
    if (!payload) {
      return NextResponse.json({ error: '无效的token' }, { status: 401 });
    }

    const { id, questionId, content, images, isPublic, question } = await request.json();

    if (!questionId || !content) {
      return NextResponse.json({ error: '请填写答案' }, { status: 400 });
    }

    // 题目在后端不存在时自动建档（题库内容在前端数据里，首次提交时同步题目）
    const existingQuestion = await prisma.dailyQuestion.findUnique({
      where: { id: questionId },
    });

    if (!existingQuestion && question) {
      try {
        await prisma.dailyQuestion.create({
          data: {
            id: questionId,
            moduleId: String(question.moduleId || 'math'),
            date: String(question.date || new Date().toISOString().slice(0, 10)),
            title: String(question.title || '每日一题'),
            content: String(question.content || content),
            images: Array.isArray(question.images) ? question.images : [],
            answer: question.answer ? String(question.answer) : null,
            answerImages: Array.isArray(question.answerImages) ? question.answerImages : [],
            difficulty: typeof question.difficulty === 'number' ? question.difficulty : 3,
            isAutoGenerated: question.isAutoGenerated !== false,
          },
        });
      } catch (createError) {
        console.warn('创建题目失败（可能已存在）:', createError);
      }
    }

    // AI判卷（简化版，实际应调用AI服务）
    const aiScore = Math.floor(Math.random() * 40) + 60; // 模拟60-100分
    const isCorrect = aiScore >= 80;
    const experienceGained = isCorrect ? 20 : aiScore >= 60 ? 10 : 5;

    // 创建答题记录
    const answer = await prisma.answerRecord.create({
      data: {
        ...(id ? { id } : {}),
        userId: payload.userId,
        questionId,
        content,
        images: images || [],
        aiScore,
        aiFeedback: isCorrect ? '回答正确，思路清晰！' : '回答基本正确，但还有改进空间。',
        isCorrect,
        experienceGained,
        isPublic: !!isPublic,
      },
    });

    return NextResponse.json({
      answer,
      feedback: answer.aiFeedback,
      score: answer.aiScore,
      expGained: experienceGained,
    });
  } catch (error) {
    console.error('提交答案失败:', error);
    return NextResponse.json({ error: '提交答案失败' }, { status: 500 });
  }
}

// 获取用户的答题记录
export async function GET(request: NextRequest) {
  try {
    const token = request.headers.get('authorization')?.replace('Bearer ', '');

    if (!token) {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }

    const payload = verifyToken(token);
    if (!payload) {
      return NextResponse.json({ error: '无效的token' }, { status: 401 });
    }

    const answers = await prisma.answerRecord.findMany({
      where: { userId: payload.userId },
      orderBy: { submittedAt: 'desc' },
      include: {
        question: {
          select: {
            id: true,
            title: true,
            moduleId: true,
          },
        },
      },
    });

    return NextResponse.json({ answers });
  } catch (error) {
    console.error('获取答题记录失败:', error);
    return NextResponse.json({ error: '获取答题记录失败' }, { status: 500 });
  }
}
