import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken } from '@/lib/auth';

import { gradeAnswerServer, sanitizeGradingImages } from '@/lib/server-grader';
import { getDailyQuestionByIdFallback } from '@/lib/ai-question-generator';

// 提交答案
export async function POST(request: NextRequest) {
  try {
    const token = request.headers.get('authorization')?.replace('Bearer ', '');

    if (!token) {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }

    const payload = verifyToken(token);
    if (!payload) {
      return NextResponse.json({ error: '无效的token' }, { status: 401 });
    }

    const { id, questionId, content, images, isPublic } = await request.json();

    if (!questionId || !content) {
      return NextResponse.json({ error: '请填写答案' }, { status: 400 });
    }

    // 题目内容以后端为准，绝不信任客户端传入的 question 对象：
    // 1. 优先查库；2. 不存在时从服务端确定性题库（daily-question-bank）按 id 推导；
    // 3. 推导不出（非每日一题 id）则拒绝，防止伪造题目/参考答案刷经验。
    let questionRecord = await prisma.dailyQuestion.findUnique({
      where: { id: questionId },
    });

    if (!questionRecord) {
      const derived = await getDailyQuestionByIdFallback(questionId);
      if (!derived) {
        return NextResponse.json({ error: '题目不存在' }, { status: 404 });
      }
      try {
        questionRecord = await prisma.dailyQuestion.create({
          data: {
            id: derived.id,
            moduleId: derived.moduleId,
            date: derived.date,
            title: derived.title,
            content: derived.content,
            images: derived.images ?? [],
            answer: derived.answer ?? null,
            answerImages: derived.answerImages ?? [],
            difficulty: derived.difficulty ?? 3,
            isAutoGenerated: true,
          },
        });
      } catch (createError) {
        // 并发下可能已被其他请求创建，重新读取
        console.warn('创建题目失败（可能已存在）:', createError);
        questionRecord = await prisma.dailyQuestion.findUnique({
          where: { id: questionId },
        });
        if (!questionRecord) {
          return NextResponse.json({ error: '题目初始化失败' }, { status: 500 });
        }
      }
    }

    const questionForGrading = {
      title: questionRecord.title,
      content: questionRecord.content,
      answer: questionRecord.answer,
    };

    // 判卷链路：识图判卷（有图且有 Key）→ 文本 AI 判卷（DeepSeek）→ 不记分
    // 注意：判卷不可用时不得给随机分（此前实现可被反复提交刷经验）
    const grading = await gradeAnswerServer(
      questionForGrading,
      content,
      sanitizeGradingImages(images)
    );

    const experienceGained = grading
      ? grading.isCorrect
        ? 20
        : grading.score >= 60
          ? 10
          : 5
      : 0;

    // 创建答题记录
    const answer = await prisma.answerRecord.create({
      data: {
        ...(id ? { id } : {}),
        userId: payload.userId,
        questionId,
        content,
        images: sanitizeGradingImages(images),
        aiScore: grading?.score ?? 0,
        aiFeedback: grading?.feedback ?? 'AI 判卷暂不可用，本次提交不记分',
        isCorrect: grading?.isCorrect ?? false,
        experienceGained,
        isPublic: !!isPublic,
      },
    });

    return NextResponse.json({
      answer,
      feedback: answer.aiFeedback,
      score: answer.aiScore,
      expGained: experienceGained,
    });
  } catch (error) {
    console.error('提交答案失败:', error);
    return NextResponse.json({ error: '提交答案失败' }, { status: 500 });
  }
}

// 获取用户的答题记录
export async function GET(request: NextRequest) {
  try {
    const token = request.headers.get('authorization')?.replace('Bearer ', '');

    if (!token) {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }

    const payload = verifyToken(token);
    if (!payload) {
      return NextResponse.json({ error: '无效的token' }, { status: 401 });
    }

    const answers = await prisma.answerRecord.findMany({
      where: { userId: payload.userId },
      orderBy: { submittedAt: 'desc' },
      include: {
        question: {
          select: {
            id: true,
            title: true,
            moduleId: true,
          },
        },
      },
    });

    return NextResponse.json({ answers });
  } catch (error) {
    console.error('获取答题记录失败:', error);
    return NextResponse.json({ error: '获取答题记录失败' }, { status: 500 });
  }
}
