import { NextRequest, NextResponse } from 'next/server';
import { getClientIp, rateLimit } from '@/lib/rate-limit';

// AI 出题接口：服务端调用 DeepSeek 生成每日一题，避免在前端暴露 API Key。
// 同一天同一科目只生成一次（实例内缓存），所有用户拿到同一道题，也降低调用成本。

const VALID_MODULES = ['highschool-math', 'advanced-math', 'linear-algebra'] as const;

const PROMPT_TEMPLATES: Record<string, string> = {
  'highschool-math': `你是一位资深高中数学竞赛教练。请出一道高难度的高中数学题目，要求：

1. **难度等级**：高考压轴题或数学竞赛初赛水平
2. **知识点范围**：函数与方程、数列、解析几何、导数应用、不等式证明、立体几何
3. **题目类型**：综合性大题，需要多步骤推理
4. **具体要求**：
   - 题目要有一定的创新性和思维深度
   - 避免陈题，设计新颖的情境或角度
   - 解答需要运用多种数学方法和技巧
   - 计算量适中，重思维轻计算

5. **输出格式**（严格遵循，纯 JSON，不要 markdown 代码块标记）：
   {
     "title": "题目标题（15字以内）",
     "content": "题目内容，使用LaTeX格式书写数学公式，行内公式用 $...$，独立公式用 $$...$$",
     "answer": "详细解答过程，包含完整步骤和最终答案",
     "difficulty": 5
   }

注意：题目必须是原创的，不要直接复制经典竞赛题。`,

  'advanced-math': `你是一位大学数学教授。请出一道高难度的高等数学题目，要求：

1. **难度等级**：985高校期末考试难题或研究生入学考试水平
2. **知识点范围**：多元函数微积分、重积分、曲线曲面积分、无穷级数、常微分方程
3. **题目类型**：计算与证明结合的综合性题目
4. **具体要求**：
   - 涉及多个知识点的交叉应用
   - 需要灵活运用各种定理和技巧
   - 考查对概念本质的理解深度
   - 可以是带有物理或几何背景的数学建模问题

5. **输出格式**（严格遵循，纯 JSON，不要 markdown 代码块标记）：
   {
     "title": "题目标题（15字以内）",
     "content": "题目内容，使用LaTeX格式书写数学公式，行内公式用 $...$，独立公式用 $$...$$",
     "answer": "详细解答过程，包含完整推导和最终答案",
     "difficulty": 5
   }

注意：题目应具有学术严谨性，避免计算过于繁琐。`,

  'linear-algebra': `你是一位线性代数专家。请出一道高难度的线性代数题目，要求：

1. **难度等级**：数学系本科高年级或研究生水平
2. **知识点范围**：矩阵理论、特征值与特征向量、二次型、线性空间、线性变换
3. **题目类型**：理论推导与计算结合
4. **具体要求**：
   - 涉及抽象代数概念的深入理解
   - 需要构造反例或证明一般性结论
   - 可涉及多种标准形的应用
   - 考查对线性代数几何意义的理解

5. **输出格式**（严格遵循，纯 JSON，不要 markdown 代码块标记）：
   {
     "title": "题目标题（15字以内）",
     "content": "题目内容，使用LaTeX格式书写数学公式，行内公式用 $...$，独立公式用 $$...$$",
     "answer": "详细解答过程，包含完整推导和最终答案",
     "difficulty": 5
   }

注意：强调线性代数的结构美感和内在联系。`,
};

// 实例内缓存：key = `${date}-${moduleId}`，避免同一天同一科目重复调用 AI
const questionCache = new Map<string, GeneratedQuestion>();
const CACHE_MAX = 200;

interface GeneratedQuestion {
  id: string;
  moduleId: string;
  date: string;
  title: string;
  content: string;
  images: string[];
  answer: string;
  answerImages: string[];
  difficulty: number;
  isAutoGenerated: boolean;
  createdAt: string;
}

function buildPrompt(moduleId: string, date: string): string {
  // 随机种子让模型跳出经典例题的采样热点
  const seed = Math.floor(Math.random() * 1000000);
  return `${PROMPT_TEMPLATES[moduleId]}

今天是${date}，请出一道新颖的题目（随机种子：${seed}），避免常见的经典例题。`;
}

function extractJson(text: string): Record<string, unknown> {
  let jsonStr = text.trim();
  if (jsonStr.startsWith('```')) {
    jsonStr = jsonStr.replace(/^```(?:json)?\s*/, '').replace(/```\s*$/, '');
  }
  return JSON.parse(jsonStr);
}

function pruneCache(today: string) {
  // 只保留今天的缓存；条目过多时清空
  if (questionCache.size < CACHE_MAX) {
    for (const key of questionCache.keys()) {
      if (!key.startsWith(today)) questionCache.delete(key);
    }
    return;
  }
  questionCache.clear();
}

export async function POST(request: NextRequest) {
  const apiKey = process.env.DEEPSEEK_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ aiAvailable: false, reason: 'no_api_key' });
  }

  // 限流：每 IP 每分钟最多 20 次（缓存命中不计成本，但防止恶意刷接口）
  const limited = rateLimit(`qgen:${getClientIp(request)}`, 20, 60 * 1000);
  if (limited) return limited;

  try {
    const body = await request.json().catch(() => ({}));
    const moduleId = String(body?.moduleId || '');
    const date = String(body?.date || '');

    if (!VALID_MODULES.includes(moduleId as (typeof VALID_MODULES)[number])) {
      return NextResponse.json({ aiAvailable: false, reason: 'invalid_module' }, { status: 400 });
    }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      return NextResponse.json({ aiAvailable: false, reason: 'invalid_date' }, { status: 400 });
    }

    const cacheKey = `${date}-${moduleId}`;
    const cached = questionCache.get(cacheKey);
    if (cached) {
      return NextResponse.json({ aiAvailable: true, question: cached, cached: true });
    }

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 30000);
    const response = await fetch('https://api.deepseek.com/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [{ role: 'user', content: buildPrompt(moduleId, date) }],
        temperature: 0.8,
        max_tokens: 2000,
        response_format: { type: 'json_object' },
      }),
      signal: controller.signal,
    });
    clearTimeout(timer);

    if (!response.ok) {
      console.warn('DeepSeek 出题 HTTP 错误:', response.status);
      return NextResponse.json({ aiAvailable: false });
    }

    const data = await response.json();
    const text = data?.choices?.[0]?.message?.content;
    if (!text) {
      return NextResponse.json({ aiAvailable: false });
    }

    const parsed = extractJson(String(text));
    if (!parsed.title || !parsed.content) {
      return NextResponse.json({ aiAvailable: false });
    }

    const question: GeneratedQuestion = {
      id: `daily-${date}-${moduleId}`,
      moduleId,
      date,
      title: String(parsed.title).slice(0, 100),
      content: String(parsed.content),
      images: [],
      answer: parsed.answer ? String(parsed.answer) : '',
      answerImages: [],
      difficulty: Math.min(5, Math.max(1, Number(parsed.difficulty) || 3)),
      isAutoGenerated: true,
      createdAt: new Date().toISOString(),
    };

    pruneCache(date);
    questionCache.set(cacheKey, question);

    return NextResponse.json({ aiAvailable: true, question });
  } catch (error) {
    console.warn('AI 出题失败:', error);
    return NextResponse.json({ aiAvailable: false });
  }
}
